# Generated by Django 5.0.6 on 2024-05-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
    ]
