# Generated by Django 5.0.6 on 2024-05-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
